apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kad
  namespace: argo
spec:
  destination:
    name: kad
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm
    repoURL: https://github.com/pencakj/k8s-training.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
